/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AuthController_updateMe"];
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/polls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PollsController_list"];
        put?: never;
        post: operations["PollsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/polls/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PollsController_get"];
        put?: never;
        post?: never;
        delete: operations["PollsController_remove"];
        options?: never;
        head?: never;
        patch: operations["PollsController_update"];
        trace?: never;
    };
    "/polls/{id}/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["PollsController_toggleActive"];
        trace?: never;
    };
    "/admin/polls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminPollsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/polls/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminPollsController_getOne"];
        put?: never;
        post?: never;
        delete: operations["AdminPollsController_remove"];
        options?: never;
        head?: never;
        patch: operations["AdminPollsController_update"];
        trace?: never;
    };
    "/admin/polls/{id}/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AdminPollsController_toggleActive"];
        trace?: never;
    };
    "/public/polls/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ResponsesController_getPublic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/polls/{slug}/responses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ResponsesController_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/polls/{id}/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AnalyticsController_getOwnerAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/polls/{pollId}/questions/{questionId}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AnalyticsController_analyzeFreeTextQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/polls/{id}/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AnalyticsController_getAdminPollAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AnalyticsController_getSystemAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UsersController_changeRole"];
        trace?: never;
    };
    "/admin/users/bulk-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UsersController_bulkDelete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_exportCsv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example alice@example.com */
            email: string;
            /** @example Alice Example */
            name: string;
            password: string;
        };
        AuthUserDto: {
            id: string;
            email: string;
            name: string;
            /** @enum {string} */
            role: "USER" | "ADMIN";
        };
        AuthResponseDto: {
            user: components["schemas"]["AuthUserDto"];
        };
        LoginDto: {
            email: string;
            password: string;
        };
        UpdateMeDto: {
            /** @example Alice Example */
            name?: string;
            /** @example alice@example.com */
            email?: string;
        };
        ChangePasswordDto: {
            currentPassword: string;
            newPassword: string;
        };
        PollSummaryDto: {
            id: string;
            slug: string;
            title: string;
            description?: string;
            /** @enum {string} */
            visibility: "PUBLIC" | "PRIVATE";
            isActive: boolean;
            /** Format: date-time */
            expiresAt?: string;
            responseCount: number;
            createdAt: string;
        };
        PollListResponseDto: {
            items: components["schemas"]["PollSummaryDto"][];
            total: number;
            page: number;
            pageSize: number;
        };
        OptionInputDto: {
            text: string;
        };
        QuestionInputDto: {
            /** @enum {string} */
            type: "SINGLE_CHOICE" | "MULTIPLE_CHOICE" | "TEXT";
            text: string;
            /** @default false */
            isRequired: boolean;
            options: components["schemas"]["OptionInputDto"][];
        };
        CreatePollDto: {
            title: string;
            description?: string;
            /**
             * @default PRIVATE
             * @enum {string}
             */
            visibility: "PUBLIC" | "PRIVATE";
            /** @default true */
            isActive: boolean;
            /** Format: date-time */
            expiresAt?: string;
            questions: components["schemas"]["QuestionInputDto"][];
        };
        OptionDto: {
            id: string;
            text: string;
            order: number;
        };
        QuestionDto: {
            id: string;
            order: number;
            /** @enum {string} */
            type: "SINGLE_CHOICE" | "MULTIPLE_CHOICE" | "TEXT";
            text: string;
            isRequired: boolean;
            options: components["schemas"]["OptionDto"][];
        };
        PollDetailDto: {
            id: string;
            slug: string;
            title: string;
            description?: string;
            /** @enum {string} */
            visibility: "PUBLIC" | "PRIVATE";
            isActive: boolean;
            /** Format: date-time */
            expiresAt?: string;
            responseCount: number;
            createdAt: string;
            questions: components["schemas"]["QuestionDto"][];
        };
        UpdatePollDto: {
            title: string;
            description?: string;
            /**
             * @default PRIVATE
             * @enum {string}
             */
            visibility: "PUBLIC" | "PRIVATE";
            /** @default true */
            isActive: boolean;
            /** Format: date-time */
            expiresAt?: string;
            questions: components["schemas"]["QuestionInputDto"][];
        };
        ToggleActiveDto: {
            isActive: boolean;
        };
        PublicPollDto: {
            id: string;
            title: string;
            description?: string;
            /** Format: date-time */
            expiresAt?: string;
            closed: boolean;
            questions: components["schemas"]["QuestionDto"][];
        };
        AnswerInputDto: {
            questionId: string;
            optionIds?: string[];
            textValue?: string;
        };
        SubmitResponseDto: {
            answers: components["schemas"]["AnswerInputDto"][];
        };
        SubmitResultDto: {
            submittedAt: string;
        };
        OptionAggregateDto: {
            optionId: string;
            text: string;
            order: number;
            count: number;
        };
        QuestionAggregateDto: {
            questionId: string;
            text: string;
            order: number;
            /** @enum {string} */
            type: "SINGLE_CHOICE" | "MULTIPLE_CHOICE" | "TEXT";
            answerCount: number;
            options: components["schemas"]["OptionAggregateDto"][];
            /** @description Number of distinct text answers, for TEXT questions only */
            textAnswerCount?: number;
        };
        OwnerAnalyticsDto: {
            pollId: string;
            title: string;
            totalResponses: number;
            questions: components["schemas"]["QuestionAggregateDto"][];
        };
        SentimentDto: {
            /** @description Percentage of positive answers (0-100, integer) */
            positive: number;
            /** @description Percentage of neutral answers (0-100, integer) */
            neutral: number;
            /** @description Percentage of negative answers (0-100, integer) */
            negative: number;
        };
        ThemeDto: {
            /** @description Short theme label, lowercase token */
            label: string;
            /** @description Number of answers mentioning the theme */
            count: number;
            /** @description Verbatim answer fragment, ≤ 140 chars */
            quote: string;
        };
        AiAnalysisDto: {
            /** @description One-sentence summary of the responses */
            summary: string;
            sentiment: components["schemas"]["SentimentDto"];
            /** @description 0–5 themes ordered by frequency */
            themes: components["schemas"]["ThemeDto"][];
        };
        SystemAnalyticsDto: {
            totalUsers: number;
            totalAdmins: number;
            totalPolls: number;
            activePolls: number;
            totalResponses: number;
        };
        UserSummaryDto: {
            id: string;
            email: string;
            name: string;
            /** @enum {string} */
            role: "USER" | "ADMIN";
            /** Format: date-time */
            createdAt: string;
        };
        UserListResponseDto: {
            items: components["schemas"]["UserSummaryDto"][];
            total: number;
            page: number;
            pageSize: number;
        };
        ChangeRoleDto: {
            /** @enum {string} */
            role: "USER" | "ADMIN";
        };
        BulkDeleteDto: {
            ids: string[];
        };
        BulkDeleteResultDto: {
            count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserDto"];
                };
            };
        };
    };
    AuthController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserDto"];
                };
            };
        };
    };
    AuthController_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PollsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollListResponseDto"];
                };
            };
        };
    };
    PollsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePollDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollDetailDto"];
                };
            };
        };
    };
    PollsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollDetailDto"];
                };
            };
        };
    };
    PollsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PollsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePollDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollDetailDto"];
                };
            };
        };
    };
    PollsController_toggleActive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToggleActiveDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollSummaryDto"];
                };
            };
        };
    };
    AdminPollsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollListResponseDto"];
                };
            };
        };
    };
    AdminPollsController_getOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollDetailDto"];
                };
            };
        };
    };
    AdminPollsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminPollsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePollDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollDetailDto"];
                };
            };
        };
    };
    AdminPollsController_toggleActive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToggleActiveDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollSummaryDto"];
                };
            };
        };
    };
    ResponsesController_getPublic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicPollDto"];
                };
            };
        };
    };
    ResponsesController_submit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitResponseDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitResultDto"];
                };
            };
        };
    };
    AnalyticsController_getOwnerAnalytics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerAnalyticsDto"];
                };
            };
        };
    };
    AnalyticsController_analyzeFreeTextQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pollId: string;
                questionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiAnalysisDto"];
                };
            };
        };
    };
    AnalyticsController_getAdminPollAnalytics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerAnalyticsDto"];
                };
            };
        };
    };
    AnalyticsController_getSystemAnalytics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemAnalyticsDto"];
                };
            };
        };
    };
    UsersController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponseDto"];
                };
            };
        };
    };
    UsersController_changeRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeRoleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummaryDto"];
                };
            };
        };
    };
    UsersController_bulkDelete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkDeleteDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkDeleteResultDto"];
                };
            };
        };
    };
    UsersController_exportCsv: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
