/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/polls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PollsController_list"];
        put?: never;
        post: operations["PollsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/polls/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PollsController_get"];
        put?: never;
        post?: never;
        delete: operations["PollsController_remove"];
        options?: never;
        head?: never;
        patch: operations["PollsController_update"];
        trace?: never;
    };
    "/polls/{id}/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["PollsController_toggleActive"];
        trace?: never;
    };
    "/public/polls/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ResponsesController_getPublic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/polls/{slug}/responses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ResponsesController_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example alice@example.com */
            email: string;
            /** @example Alice Example */
            name: string;
            password: string;
        };
        AuthUserDto: {
            id: string;
            email: string;
            name: string;
            /** @enum {string} */
            role: "USER" | "ADMIN";
        };
        AuthResponseDto: {
            user: components["schemas"]["AuthUserDto"];
        };
        LoginDto: {
            email: string;
            password: string;
        };
        PollSummaryDto: {
            id: string;
            slug: string;
            title: string;
            description?: string;
            /** @enum {string} */
            visibility: "PUBLIC" | "PRIVATE";
            isActive: boolean;
            /** Format: date-time */
            expiresAt?: string;
            responseCount: number;
            createdAt: string;
        };
        PollListResponseDto: {
            items: components["schemas"]["PollSummaryDto"][];
            total: number;
            page: number;
            pageSize: number;
        };
        OptionInputDto: {
            text: string;
        };
        QuestionInputDto: {
            /** @enum {string} */
            type: "SINGLE_CHOICE" | "MULTIPLE_CHOICE" | "TEXT";
            text: string;
            /** @default false */
            isRequired: boolean;
            options: components["schemas"]["OptionInputDto"][];
        };
        CreatePollDto: {
            title: string;
            description?: string;
            /**
             * @default PRIVATE
             * @enum {string}
             */
            visibility: "PUBLIC" | "PRIVATE";
            /** @default true */
            isActive: boolean;
            /** Format: date-time */
            expiresAt?: string;
            questions: components["schemas"]["QuestionInputDto"][];
        };
        OptionDto: {
            id: string;
            text: string;
            order: number;
        };
        QuestionDto: {
            id: string;
            order: number;
            /** @enum {string} */
            type: "SINGLE_CHOICE" | "MULTIPLE_CHOICE" | "TEXT";
            text: string;
            isRequired: boolean;
            options: components["schemas"]["OptionDto"][];
        };
        PollDetailDto: {
            id: string;
            slug: string;
            title: string;
            description?: string;
            /** @enum {string} */
            visibility: "PUBLIC" | "PRIVATE";
            isActive: boolean;
            /** Format: date-time */
            expiresAt?: string;
            responseCount: number;
            createdAt: string;
            questions: components["schemas"]["QuestionDto"][];
        };
        UpdatePollDto: {
            title: string;
            description?: string;
            /**
             * @default PRIVATE
             * @enum {string}
             */
            visibility: "PUBLIC" | "PRIVATE";
            /** @default true */
            isActive: boolean;
            /** Format: date-time */
            expiresAt?: string;
            questions: components["schemas"]["QuestionInputDto"][];
        };
        ToggleActiveDto: {
            isActive: boolean;
        };
        PublicPollDto: {
            id: string;
            title: string;
            description?: string;
            /** Format: date-time */
            expiresAt?: string;
            closed: boolean;
            questions: components["schemas"]["QuestionDto"][];
        };
        AnswerInputDto: {
            questionId: string;
            optionIds?: string[];
            textValue?: string;
        };
        SubmitResponseDto: {
            answers: components["schemas"]["AnswerInputDto"][];
        };
        SubmitResultDto: {
            submittedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserDto"];
                };
            };
        };
    };
    PollsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollListResponseDto"];
                };
            };
        };
    };
    PollsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePollDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollDetailDto"];
                };
            };
        };
    };
    PollsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollDetailDto"];
                };
            };
        };
    };
    PollsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PollsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePollDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollDetailDto"];
                };
            };
        };
    };
    PollsController_toggleActive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToggleActiveDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollSummaryDto"];
                };
            };
        };
    };
    ResponsesController_getPublic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicPollDto"];
                };
            };
        };
    };
    ResponsesController_submit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitResponseDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitResultDto"];
                };
            };
        };
    };
}
